title: Blog Bibliotheks- und Archivinformatik
author: Lucien
email: lucien.haeller@stud.fhgr.ch
description: > # this means to ignore newlines
  Lerntagebuch im Kurs Bibliotheks- und Archivinformatik HS2021

# social links
github_username:  lhaeller # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
